= 2. Scope

This interoperability standard defines NSG implementable provisions that profile the OGC GeoPackage standard to ensure that NSG GeoPackages, GeoPackage SQLite Extensions, and supporting utilities and services fulfil their intended purposes and are fit for use.

This interoperability standard will be used by government, commercial, open source, and Non-Governmental Organizations (NGOs):

* *Data Providers* deliver NSG GeoPackage data files. They may employ software provided by both Infrastructure Providers and Application Software Providers.
* *Infrastructure Software Providers* deliver software that implements the SQLite engine, GeoPackage SQLite Extensions, GeoPackage libraries and/or stand-alone GeoPackage utilities or web services to encode/decode, validate, and manage GeoPackage files.
* *Application Software Providers* deliver GeoPackage “Apps” that provide users with the capabilities they require in general or mission-specific environments. They may employ software provided by Infrastructure Providers and bundle their Apps with GeoPackages from Data Providers.
* *DoD/IC Procurement Organizations* acquire conformant GeoPackages, infrastructure, and applications.

Architects, systems and software engineers, developers, and data modelers of the NSG and its component systems/applications in these roles will promote uniform geospatial data access, GeoPackage and GeoPackage SQLite Extension development and use. The goal is to increase interoperability, modularity, and agility of applications within the NSG. This interoperability standard is an adjunct to the base standard profiled – not a stand-alone document.

This document requires adherence to all GeoPackage OGC Specification normative clauses and normative annexes, and to the normative provisions herein that restrict the clauses summarized in Table 1.

[[_Ref455132081]]Table 1: Profile / Standard Clause Crosswalk

[cols=",",options="header",]
|================================================================================================
|*NSG GeoPackage Profile Clause* |*GeoPackage Encoding Standard Clause*
|6.1 File Names |1.1.1.1.2 File Extension Name
|6.2 Extensions |2.3.2 Extensions
|7.1 Coordinate Reference Systems |1.1.2.1.2 Spatial Reference Systems / Data / Table Data Values
|7.3 Metadata |Annex F.8
|7.3 Metadata |Annex F.8
|7.3Metadata |3 Security Considerations
|7.4 Data Validity Constraints |1.1.2.1 Spatial Reference Systems / Data
|7.4 Data Validity Constraints |1.1.3.1 Contents / Data
|7.4 Data Validity Constraints |2.1.5.1 Geometry Columns / Data
|7.4 Data Validity Constraints |2.1.6.1 Vector Feature User Data Tables / Data
|7.4 Data Validity Constraints |2.2.7.1 Tile Matrix / Data
|7.4 Data Validity Constraints |2.2.8.1 Tile Pyramid user Data Tables / Data
|7.4 Data Validity Constraints |Annex F.8
|7.4 Data Validity Constraints |Annex F.8
|7.4 Data Validity Constraints |Annex E
|8.1 Tile Size |2.2.7.1 Tile Matrix / Data
|8.1 Tile Size |2.2.8.1 Tile Pyramid User Data Tables / Data
|8.2 Zoom Levels |2.2.3 Tiles / Zoom Levels
|8.2 Zoom Levels |2.2.7.1 Tile Matrix / Data
|8.2 Zoom Levels |2.2.8.1 Tile Pyramid User Data Tables / Data
|8.2 Zoom Levels |2.2.3 Tiles / Zoom Levels
|8.3 Bounding Boxes |1.1.3.1 Contents / Data
|8.3 Bounding Boxes |2.2.6 Tile Matrix Set
|9.1 GeoPackage Extensions |Annex F.2
|9.1 GeoPackage Extensions |Annex F.3
|9.1 GeoPackage Extensions |Annex F.4
|================================================================================================

When used in this document, the term “shall” indicates a firm, mandatory requirement; whereas, the terms “may”, “will”, and “should” identify non-mandatory requirements.

Not all clauses of this Interoperability Standard apply to all NSG GeoPackages or GeoPackage SQLite Extensions because a particular GeoPackage may contain vector features, tile pyramids, or both.

Any comments or questions regarding the interpretation of the provisions of the NSG GeoPackage Profile are to be addressed via the appropriate governance process for NSG interoperability standards.
